# Generated by Django 5.2.6 on 2025-09-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric')], max_length=50)),
                ('price_per_week', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(upload_to='cars/')),
            ],
        ),
    ]
